version: 2
jobs:
  build:
    docker:
      - image: ruby:2.5.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
              # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Run RSpec
          command: |
            bundle install --path vendor/bundle
            bundle exec rspec
      - save_cache:
        key: 
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle
