name: test

on: [push]

jobs:
  test:
    name: Run spec
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        version: 2.6.x

    - name: Run spec
      run: |
        gem i bundler:2.1.4 --no-document --silent
        bundle install --path vendor/bundle --quiet
        bundle exec rspec spec

